[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@netlify/functions"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"

[[headers]]
  for = "/drawings/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.ai"
  [headers.values]
    Content-Type = "application/illustrator"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.docx"
  [headers.values]
    Content-Type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    Content-Disposition = "attachment"

[[headers]]
  for = "/drawings/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"

# Forms 설정
[forms]
  suggestions = "Suggestions Form" 